### ISSUE TITLE
Failure to rejoin network after several days, unplugging to reset fixes

### ISSUE THREAD

**Issue by dvorit-manylabs** [manylabs/manydoors#15]
Hi guys, thanks very much for your help on this! We will be changing the lock on the front door knob soon and so it will become even more important that door fobs work consistently. I will be back from out of town on Thurs, 4/13. If this issue can be resolved by then, that would be ideal. If you need more time, we will probably rekey the front door by Monday, 4/17.

**Comment by jhpoelen** [comment]
@dvorit-manylabs thanks for opening this issue. Just curious - is the doorbot still behaving correctly? Did you have to reset the dootbot after the reset of last Tuesday 4 April 2017?

**Comment by dvorit-manylabs** [comment]
Behaving correctly so far. I will add a new fob today and will test it to
see if it works after adding it to the repo...



*Dvorit Mausner | Manylabs *
Executive Director *|* dvorit@manylabs.org
215-873-7764 *|* Schedule a meeting <https://calendly.com/dvorit>

**Comment by dvorit-manylabs** [comment]
Good news - I programmed a new fob and it worked as expected shortly after.
Hooray! (for now)



*Dvorit Mausner | Manylabs *
Executive Director *|* dvorit@manylabs.org
215-873-7764 *|* Schedule a meeting <https://calendly.com/dvorit>

**Comment by 100ideas** [comment]
Maybe doorbot drops off the network due to an [arcane power-saving configuration option](https://learn.adafruit.com/adafruits-raspberry-pi-lesson-3-network-setup?view=all#fixing-wifi-dropout-issues)

I will update if I make this change.

> If you find your module 'drops out' from time to time, you can fix it fairly easily with a command line fix (thanks perseus286!)
> 
> Create and edit a new file in /etc/modprobe.d/8192cu.conf
>
>     sudo nano /etc/modprobe.d/8192cu.conf
>
> and paste the following in
>
>     # Disable power saving
>     options 8192cu rtw_power_mgnt=0 rtw_enusbss=1 rtw_ips_mode=1
>
> Then reboot with sudo reboot

More info on [rtl8192cu options for kernel module](https://www.raspberrypi.org/forums/viewtopic.php?f=46&t=61004)

**Comment by 100ideas** [comment]
upgraded system, removed x11 crap, and set wifi power tweaks in
1. /etc/modprobe.d/8192cu.conf
2. /etc/network/interfaces

see notes in  https://github.com/manylabs/manydoors/issues/16

---
please reopen if doorbot slack messages seem intermittent

**Comment by dvorit-manylabs** [comment]
Seems to be working today - at least seeing updates in Slack.
Many thanks, Mac!



*Dvorit Mausner | Manylabs *
Executive Director *|* dvorit@manylabs.org
215-873-7764 *|* Schedule a meeting <https://calendly.com/dvorit>
